### ISSUE TITLE
Remove notion of editors

### ISSUE THREAD

**Issue by leplatrem** [mozilla/remote-settings#150]
The editors group is used to limit the users allowed to request review on a collection.

We don't really need that. Being able to write on the collection is enough to be allowed to request review. And there is no reason why a reviewer could not request a review too (since they have write perms on the collection).

This would allow to remove a lot of duplicated lists in our permissions manifests, because for collections whose group of editors is the same as reviewers, we would just have:

```yaml
cid:
  permissions:
      write:
          - /buckets/main/groups/cid-reviewers
```

And for the collections which have editors that are not reviewers, we would do:

```yaml
cid:
   permissions:
      write:
          - ldap:editor1@mozilla.com
          - ldap:editor2@mozilla.com
          - /buckets/main/groups/cid-reviewers
```
-----

This issue was initially reported here https://github.com/Kinto/kinto-signer/issues/733

But it makes more sense to keep track of it here, along with #1945, #1946, #1948. 

--------
Imported from https://github.com/mozilla-services/kinto-dist/issues/1952
