### ISSUE TITLE
`backport_records` for multiple collections is verbose

### ISSUE THREAD

**Issue by leplatrem** [mozilla/remote-settings#733]
Currently, in order to setup the `backport_record` cronjob that will copy records from one collection to another using filters, it takes [all these config lines](https://github.com/mozilla-it/webservices-infra/pull/2953):

```yaml
  backport_records_normandy:
    hasExternalSecrets: true
    schedule: "*/10 * * * *"
    suspend: false
    image:
      repository: us-docker.pkg.dev/moz-fx-remote-settings-prod/remote-settings-prod/remote-settings-lambdas
      tag: latest
      pullPolicy: Always

    env:
      - name: "BACKPORT_RECORDS_SOURCE_BUCKET"
        value: "main"

      - name: "BACKPORT_RECORDS_DEST_BUCKET"
        value: "main-workspace"

      - name: "BACKPORT_RECORDS_SOURCE_COLLECTION"
        value: "normandy-recipes-capabilities"

      - name: "BACKPORT_RECORDS_DEST_COLLECTION"
        value: "normandy-recipes"

      - name: "BACKPORT_RECORDS_SOURCE_FILTERS"
        value: "{\"recipe.uses_only_baseline_capabilities\": true}"

      - name: "SENTRY_ENV"
        value: "prod"

    args:
      - backport_records
```

If we want to onboard for examples 10 cronjobs that will breakdown records by country/regions. This is going to be extremely verbose.

I propose that we introduce a new input var that can combine them all:

```
BACKPORT_RECORDS_MAPPINGS="main/normandy-recipes-capabilities?recipe.uses_only_baseline_capabilities=true -> main-workspace/normandy-recipes
```

and one per line for multiple values:

```yaml

env:
  - name: BACKPORT_RECORDS_MAPPINGS
    value: |
      main/shops?contains_regions=["asia"] -> main-workspace/shops-asia
      main/shops?contains_regions=["europe"] -> main-workspace/shops-europe
      main/shops?contains_regions=["north-america", "central-america", "south-america"] -> main-workspace/shops-america
```
