### ISSUE TITLE
Create a reusable GitHub Actions workflow for ingestion job to publish their container

### ISSUE THREAD

**Issue by leplatrem** [mozilla/remote-settings#908]
Create a reusable GitHub Actions workflow so that a newly onboarded cronjob only needs to call the workflow to publish a new ingestion job

```
jobs:
  publish-gar-container:
    uses: mozilla/remote-settings/.github/workflows/publish-cronjob-container.yml@main
    with:
      cronjob_name: publish-mdn-data
```
